-- ============================================================
--  StudyHub — Fix 2: id identity + missing Moodle columns
--  Run in Supabase → SQL Editor → New query
--  Safe to run multiple times.
-- ============================================================

-- ── Fix 1: Allow inserting explicit id values ─────────────────
-- Tables created via Supabase UI default to GENERATED ALWAYS AS IDENTITY.
-- We need GENERATED BY DEFAULT so we can push our own SQLite ids.
-- The DO block only alters tables where id is actually GENERATED ALWAYS.

DO $$
DECLARE
  t text;
BEGIN
  FOR t IN
    SELECT unnest(ARRAY[
      'semesters','subjects','tasks','subtasks','tags',
      'attachments','grades','notes','study_sessions','schedule_entries'
    ])
  LOOP
    IF EXISTS (
      SELECT 1 FROM information_schema.columns
      WHERE table_schema = 'public'
        AND table_name   = t
        AND column_name  = 'id'
        AND identity_generation = 'ALWAYS'
    ) THEN
      EXECUTE format('ALTER TABLE %I ALTER COLUMN id SET GENERATED BY DEFAULT', t);
      RAISE NOTICE 'Fixed identity on %', t;
    END IF;
  END LOOP;
END $$;

-- ── Fix 2: Add missing Moodle / optional columns ──────────────

-- subjects
ALTER TABLE subjects ADD COLUMN IF NOT EXISTS moodle_course_id text;

-- tasks
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS recurrence_rule       text;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS recurrence_parent_id  bigint;
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS moodle_assignment_id  text;

-- attachments
ALTER TABLE attachments ADD COLUMN IF NOT EXISTS is_folder            boolean NOT NULL DEFAULT false;
ALTER TABLE attachments ADD COLUMN IF NOT EXISTS parent_attachment_id bigint;
ALTER TABLE attachments ADD COLUMN IF NOT EXISTS moodle_file_url      text;
ALTER TABLE attachments ADD COLUMN IF NOT EXISTS storage_path         text;

-- ── Refresh PostgREST schema cache ───────────────────────────
NOTIFY pgrst, 'reload schema';
